sources:
  chronic_absenteeism:
    rename: {}
    dtype: {}
    derive: {}

  english_learner_progress:
    rename: {}
    dtype: {}
    derive: {}

  graduation_rates:
    rename: {}
      # Additional custom field mappings if needed
      # Most normalization handled automatically in ETL module
    dtype:
      county_number: "str"
      district_number: "str"
      school_number: "str"
      school_year: "str"
      graduation_rate_4_year: "float64"
      graduation_rate_5_year: "float64"
      grads_4_year_cohort: "int64"
      students_4_year_cohort: "int64"
      grads_5_year_cohort: "int64"
      students_5_year_cohort: "int64"
    derive:
      processing_date: "2025-07-18"
      data_quality_flag: "reviewed"

  kindergarten_readiness:
    rename: {}
      # Normalization handled automatically in ETL module
    dtype:
      county_number: "str"
      district_number: "str"
      school_number: "str"
      school_year: "str"
      total_percent_ready: "float64"
      number_tested: "int64"
    derive:
      processing_date: "2025-07-18"

  out_of_school_suspension:
    rename: {}
    dtype: {}
    derive: {}

  postsecondary_enrollment:
    rename: {}
    dtype: {}
    derive: {}

  postsecondary_readiness:
    rename: {}
    dtype: {}
    derive: {}

  safe_schools_events:
    rename: {}
    dtype: {}
    derive: {}

  safe_schools_climate:
    rename: {}
    dtype: {}
    derive: {}

  safe_schools_discipline:
    rename: {}
    dtype: {}
    derive: {}
      
# Example configuration for field mappings and transformations
# Add new sources here as they are onboarded